# Generated by Django 5.2.5 on 2025-08-20 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPricingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(db_index=True, max_length=64)),
                ('service_category', models.CharField(max_length=32)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('n_jobs_90d', models.IntegerField(default=0)),
                ('median_usd', models.FloatField(blank=True, null=True)),
                ('multiplier_vs_city', models.FloatField(default=1.0)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider_id', 'service_category', 'city'], name='pricing_pro_provide_995a15_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_text', models.TextField()),
                ('parsed', models.JSONField()),
                ('requested_currency', models.CharField(default='CAD', max_length=3)),
                ('fx_rate_used', models.FloatField(default=1.0)),
                ('model_version', models.CharField(max_length=50)),
                ('median', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='pricing_pri_created_578313_idx')],
            },
        ),
    ]
