# Generated by Django 4.2.23 on 2025-08-30 01:59

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='account_number',
            field=encrypted_fields.fields.EncryptedCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='institution_number',
            field=encrypted_fields.fields.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='name_on_card',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='transit_number',
            field=encrypted_fields.fields.EncryptedCharField(max_length=20),
        ),
    ]
