# Generated by Django 5.2.5 on 2025-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_photos/'),
        ),
    ]
